export const FETCH_EMPLOYEES_START = 'FETCH_EMPLOYEES_START';
export const FETCH_EMPLOYEES_SUCCESS = 'FETCH_EMPLOYEES_SUCCESS';
export const FETCH_EMPLOYEES_ERROR = 'FETCH_EMPLOYEES_ERROR';

export const SEARCH_EMPLOYESS = 'SEARCH_EMPLOYESS';

export const FILTER_EMPLOYEES_ARCHIVE = 'FILTER_EMPLOYEES_ARCHIVE';

export const FILTER_EMPLOYEES_ROLE = 'FILTER_EMPLOYEES_ROLE';

export const SORT_EMPLOYEES = 'SORT_EMPLOYEES';

export const FETCH_EMPLOYEE_START = 'FETCH_EMPLOYEE_START';
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS';
export const FETCH_EMPLOYEE_ERROR = 'FETCH_EMPLOYEE_ERROR';
export const FETCH_EMPLOYEE_DELETE_SUCCESS = 'FETCH_EMPLOYEE_DELETE_SUCCESS';

export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE';
export const RESET_CREATE_EMPLOYEE = 'RESET_CREATE_EMPLOYEE';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
export const RESET_EDIT_EMPLOYEE = 'RESET_EDIT_EMPLOYEE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';